### ISSUE TITLE
Symbols broken

### ISSUE THREAD

**Issue by turandon** [illinoisjackson/even-better-ls#12]
Hey there,
when I follow your instructions with my xfce4-terminal I get the following output:

 Bilder   connection_test.zip   Dokumente   Downloads   git   Musik   Nextcloud   Öffentlich   Schreibtisch   Videos   vm

Sofar only the icons für .pdf and .iso are working. What am I doing wrong or overseeing here?

**Comment by Noammac** [comment]
a) Did you change the terminal's font?
b) Can you please take a picture of the output?

**Comment by turandon** [comment]
My Terminalfont is 'Monospace Regular'

![2017-06-07-175027_586x186_scrot](https://user-images.githubusercontent.com/5681989/26887945-dadd32f0-4ba9-11e7-8d56-86fd712675cd.png)

Thanks for your help!!

**Comment by Noammac** [comment]
Did you install [nerd-fonts](https://github.com/ryanoasis/nerd-fonts)? If so, can you please change your font to 'Knack Regular' and try again?

**Comment by ryanoasis** [comment]
Yeah, these codes are setup to match Nerd Fonts :smile:

**Comment by mnurzia** [comment]
This can be fixed by opening xfce term preferences and changing the locale to utf-8. Try doing that and see if it works.

**Comment by turandon** [comment]
My local is already set to UTF-8.
Trying the other fonts now...

**Comment by turandon** [comment]
It works, after I installed the fonts, thank you!
