### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by umop3plsdn** [illinoisjackson/even-better-ls#31]
Trying to compile this leaves me with the following:
lib/freadseek.c: In function 'freadptrinc':
lib/freadseek.c:68:3: error: #error "Please port gnulib freadseek.c to your platform! Look at the definition of getc, getc_unlocked on your system, then report this to bug-gnulib."
  #error "Please port gnulib freadseek.c to your platform! Look at the definition of getc, getc_unlocked on your system, then report this to bug-gnulib."
   ^~~~~

**Comment by umop3plsdn** [comment]
Anyone have any ideas or get this compiled on Arch?

**Comment by shlnz** [comment]
I get the same error message on Arch.

**Comment by UnwantedTachyon** [comment]
Same here

**Comment by cartoush** [comment]
Same

**Comment by victorhgo** [comment]
I'm getting the same error, and I've looking for a fix, but I can't find an answer to that error. Anyone have any idea on how to fix it?

**Comment by lclvlm** [comment]
the same

**Comment by harrypuuter** [comment]
also got this error

**Comment by lunarfolk** [comment]
Exactly same issue for me. Note that [ls-icons](https://github.com/sebastiencs/ls-icons/issues/6) seems to have had the same issue, and fixed it. Might be interesting to get in touch with them to see if it's similar.

Edit: updating to coreutils 8.31 fixed the issue for me, I'll make a pull request. For anyone interested to try it from my repository, remember to edit install.sh accordingly.

**Comment by GalGreenfield** [comment]
I'm having an issue with it on Debian (Kubuntu), too.

**Comment by GalGreenfield** [comment]
I found this, looks useful: https://github.com/coreutils/gnulib/commit/4af4a4a71827c0bc5e0ec67af23edef4f15cee8e#diff-5bcce8ce55246264586c4aed2a45ff89

**Comment by hrqmonteiro** [comment]
> I found this, looks useful: [coreutils/gnulib@4af4a4a#diff-5bcce8ce55246264586c4aed2a45ff89](https://github.com/coreutils/gnulib/commit/4af4a4a71827c0bc5e0ec67af23edef4f15cee8e#diff-5bcce8ce55246264586c4aed2a45ff89)

Is not useful, it doesn't solve the problem.

Anyone was able to solve it? I'm having the same problem on Void Linux.

**Comment by n0nvme** [comment]
@hrqmonteiro [this fork](https://github.com/n0nvme/even-better-ls) works for me
